### ISSUE TITLE
improve the json storage

### ISSUE THREAD

**Issue by aoloe** [aoloe/hashover-next#2]
# todo
- [ ] all comments in one single json per page
  - [x] create a `simplejson` module
  - [x] get `simplejson` to read a handcrafted json
  - [ ] render the indenting in the structure
  - [ ] get `simpleson` to create the `.json` file
  - [ ] get `simplejson` to add a comment
  - [ ] get `simplejson` to delete a comment
  - [ ] implement further actions on comments
  - [ ] only put in the `.json` file the fields that are set?
- [ ] setting for the path where the comments are stored (possibly out of the htdocs)
# dtd

``` json
{
    "title": "",
    "url": "",
    "status": "",
    "last_key": 0,
    "reply": [
        {
             "key": 0,
             "body": "",
             "status": "",
             "date": "",
             "name": "",
             "email": "",
             "likes": 0,
             "reply": []
        }
    ]
}
```
# implementation
- currently the json read/write is implemented in `parsejson.php`, extending `ReadFiles`.
- it implements:
  - `query`(): reading the list of files;
  - `read()`: which is a `get()` from disk
  - `save()`: which is a `set()` to disk
  - `delete()`
    `ReadFiles` also implements:
  - a constructor: reading the main metadata file
  - `saveMetadata()`
  - `loadFiles()`: reading the list of all files

i would probably implement a "simplejson" directly implementing all the needed methods and:
- storing the metadata in files that are not hidden
- storing one metadata file per instance (no need to have the page related ones)
- storing all the comments of the page in one file.
- retrieving the comments from the json file.
